# Generated by Django 3.1.2 on 2022-11-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('length', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
                ('fast_lap', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('victories', models.IntegerField()),
                ('pole_positions', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('championships', models.IntegerField()),
                ('contract', models.IntegerField()),
                ('entry_year', models.IntegerField()),
                ('country', models.ManyToManyField(to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pilot')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.race')),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='last_winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pilot'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=70)),
                ('engine', models.CharField(max_length=70)),
                ('weight', models.IntegerField()),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pilot')),
            ],
        ),
    ]
