# Generated by Django 3.1.2 on 2022-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221110_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='fast_lap',
            field=models.TimeField(),
        ),
    ]
