# Generated by Django 3.1.2 on 2022-11-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221110_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='pilot',
        ),
        migrations.AddField(
            model_name='result',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pilot'),
        ),
    ]
