# Generated by Django 3.1.2 on 2022-11-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221110_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pilot'),
        ),
    ]
