# Generated by Django 3.1.2 on 2022-11-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221112_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.circuit'),
        ),
    ]
