# Generated by Django 4.1.3 on 2022-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_team',
            field=models.ManyToManyField(to='app.team'),
        ),
    ]
