# Generated by Django 3.1.2 on 2022-12-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20221114_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/images/pilots/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='app/static/images/profiles/'),
        ),
    ]
