# Generated by Django 3.1.2 on 2022-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221228_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/images/teams/'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/images/team_leaders/'),
        ),
    ]
